const Router = require("@koa/router");

const router = new Router();

const categoriesDB = [
  {
    titleCategory: "Бетоноводы",
    linkCatalog: "./",
  },
  {
    titleCategory: "Бетономешалки",
    linkCatalog: "./betonomeshalki",
  },
];
const catalogDB = {
  betonovody: {
    titleCategory: "Бетоноводы",
    cards: [
      {
        imgSource: "./assets/1m_truba_180_auto_jpg.jpg",
        cardTitle: "Труба бетоновода 1м",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "3900",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/truba_180_auto_jpg.jpg",
        cardTitle: "Труба бетоновода 2м",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "5400",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/truba_180_auto_jpg.jpg",
        cardTitle: "Труба бетоновода 3м",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "7200",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/betonovod_180_auto_jpg.jpg",
        cardTitle: "Труба бетоновода гибкая 2м",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "16000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/betonovod_180_auto_jpg.jpg",
        cardTitle: "Труба бетоновода гибкая 3м",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "19000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/betonovod_180_auto_jpg.jpg",
        cardTitle: "Труба бетоновода гибкая 4м",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "24000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/betonovod_180_auto_jpg.jpg",
        cardTitle: "Труба бетоновода гибкая 5м",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "27000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/betonovod_180_auto_jpg.jpg",
        cardTitle: "Труба бетоновода гибкая 6м",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "31000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/homut_180_auto_jpg.jpg",
        cardTitle: "Замок бетоновода DIN125",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "1650",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/homut_180_auto_jpg.jpg",
        cardTitle: "Замок бетоновода DIN150",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "4000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/homut_180_auto_jpg.jpg",
        cardTitle: "Замок бетоновода DIN200",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "5200",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/04001_180_auto_png.png",
        cardTitle:
          "Замок бетоновода (быстросъемный рычажный оцинкованный) D 125мм",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "2600",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/1m90gr_180_auto_jpg.jpg",
        cardTitle: "Колено бетоновода 125*1000*90гр 8мм",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "9200",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/1m90gr_180_auto_jpg.jpg",
        cardTitle: "Колено бетоновода 125*1000*90гр 6мм",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "7300",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/45gr_180_auto_jpg.jpg",
        cardTitle: "Колено бетоновода 125*1000*90гр 6мм",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "5100",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/90gr_180_auto_jpg.jpg",
        cardTitle: "Колено бетоновода 125*500*90гр",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "6700",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/45gr_180_auto_jpg.jpg",
        cardTitle: "Колено бетоновода 125*500*45гр",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "3500",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/90gr_180_auto_jpg.jpg",
        cardTitle: "Колено бетоновода 125*350*90гр",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "5550",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/90gr_180_auto_jpg.jpg",
        cardTitle: "Колено бетоновода 125*275*90гр",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "5300",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/45gr_180_auto_jpg.jpg",
        cardTitle: "Колено бетоновода 125*275*45гр",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "3300",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/kb2_180_auto_png.png",
        cardTitle: "Колено поворотное HG 15",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "12900",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/20ec0b4070e8e11924b55fcfdb4a8976_180_auto_jpg.jpg",
        cardTitle: "Клапан отсечной (запорный клапан бетоновода D125 мм)",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "13000",
        priceMeasure: "₽",
      },
      {
        imgSource:
          "./assets/rezinovoe_uplotnenie_dlya_zamka_betonovoda_125_mm_180_auto_jpeg.jpeg",
        cardTitle: "Уплотнение D125 мм для замка бетононасоса",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "150",
        priceMeasure: "₽",
      },
      {
        imgSource:
          "./assets/rezinovoe_uplotnenie_dlya_zamka_betonovoda_125_mm_180_auto_jpeg.jpeg",
        cardTitle: "Уплотнение D150 мм для замка бетононасоса",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "600",
        priceMeasure: "₽",
      },
      {
        imgSource:
          "./assets/rezinovoe_uplotnenie_dlya_zamka_betonovoda_125_mm_180_auto_jpeg.jpeg",
        cardTitle: "Уплотнение D175 мм для замка бетононасоса",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "600",
        priceMeasure: "₽",
      },
      {
        imgSource:
          "./assets/rezinovoe_uplotnenie_dlya_zamka_betonovoda_125_mm_180_auto_jpeg.jpeg",
        cardTitle: "Шар промывочный D125 (жесткий/мягкий)",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "900",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/f17c1798188ceca04333d4f82fbd3830_180_auto_jpg.jpg",
        cardTitle: "Шар промывочный D125 (жесткий/мягкий)",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "900",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/pyzh-promyvochnyj_180_auto_jpg.jpg",
        cardTitle: "Цилиндр промывочный губчатый",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "1000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/1647915602808_bulletin_180_auto_jpeg.jpeg",
        cardTitle: "Комплект крепления трассы бетоновода к стене",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "",
        description: "",
        price: "5000",
        priceMeasure: "₽",
      },
      {
        imgSource: "",
        cardTitle:
          "Это тест без фото, артикула, производителя, ресурса и описания",
        cardArticle: "",
        producer: "",
        resource: "",
        resourceMeasure: "м3",
        description: "",
        price: "",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/180*180.jpg",
        cardTitle:
          "Это тест с фото, артикулом, производителем, ресурсом и описанием",
        cardArticle: "1123457AVC",
        producer: "StarkFirm",
        resource: "100 000",
        resourceMeasure: "м3",
        description:
          "Какое то описание невроятного чегото, что действительно будет служить долго как Папа Карло который пилит своего Буратино",
        price: "",
        priceMeasure: "",
      },
      {
        imgSource: "./assets/180*180.jpg",
        cardTitle:
          "Это тест с фото, артикулом, производителем, ресурсом и описанием",
        cardArticle: "1123457AVC",
        producer: "StarkFirm",
        resource: "100 000",
        resourceMeasure: "м3",
        description:
          "Какое то описание невроятного чегото, что действительно будет служить долго как Папа Карло который пилит своего Буратино",
        price: "5000",
        priceMeasure: "₽",
      },
    ],
  },
  betonomeshalki: {
    titleCategory: "Бетономешалки",
    cards: [
      {
        imgSource: "./assets/jzc350-es_180_auto_jpg.jpg",
        cardTitle: "Стационарная бетономешалка JZC 350",
        cardArticle: "",
        producer: "JZC",
        resource: "",
        resourceMeasure: "м3",
        description:
          " Бетоносмесительная установка JZC 350 гравитационного типа. Разовая выгрузка 350 литров. Оснащена скиповым подъемником, насосом для закачки воды",
        price: "390000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/js500_180_auto_png.png",
        cardTitle: "Стационарная бетономешалка JS 500",
        cardArticle: "",
        producer: "JZC",
        resource: "",
        resourceMeasure: "м3",
        description:
          " Смеситель горизонтальный двухвальный для бетонных заводов Разовая выгрузка 500 литров. Оснащена скиповым подъемником, насосом для закачки воды, компрессором вид смесителя - двухвальный ",
        price: "1180000",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/2022-06-23_13-58-33_180_auto_png.png",
        cardTitle: "Мобильная самозагружающаяся бетономешалка JZC 750",
        cardArticle: "",
        producer: "JZC",
        resource: "",
        resourceMeasure: "м3",
        description:
          "Разовая выгрузка 750 литров. Оснащена скиповым подъемником, насосом для закачки воды вид смесителя - гравитационный",
        price: "790000",
        priceMeasure: "₽",
      },
    ],
  },
  truby: {
    titleCategory: "Трубы",
    cards: [
      {
        imgSource: "./assets/180*180.jpg",
        cardTitle: "Труба на 50",
        cardArticle: "1123457AVC",
        producer: "StarkFirm",
        resource: "150 000",
        resourceMeasure: "м3",
        description:
          "Какое то описание невроятного чегото, что действительно будет служить долго как Папа Карло который пилит своего Буратино",
        price: "По запросу",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/180*180.jpg",
        cardTitle: "Труба на 70",
        cardArticle: "1123457AVC",
        producer: "StarkFirm",
        resource: "100 000",
        resourceMeasure: "м3",
        description:
          "Какое то описание невроятного чегото, что действительно будет служить долго как Папа Карло который пилит своего Буратино",
        price: "По запросу",
        priceMeasure: "₽",
      },
      {
        imgSource: "./assets/180*180.jpg",
        cardTitle: "Труба на 50",
        cardArticle: "1123457AVC",
        producer: "StarkFirm",
        resource: "150 000",
        resourceMeasure: "м3",
        description:
          "Какое то описание невроятного чегото, что действительно будет служить долго как Папа Карло который пилит своего Буратино",
        price: "По запросу",
        priceMeasure: "₽",
      },
    ],
  },
};

router.get("/", async (ctx) => {
  await ctx.render("/catalog", {
    categories: categoriesDB,
    catalog: catalogDB.betonovody,
  });
});

router.get("/betonomeshalki", async (ctx) => {
  await ctx.render("/catalog", {
    categories: categoriesDB,
    catalog: catalogDB.betonomeshalki,
  });
});

router.get("/contacts", async (ctx) => {
  await ctx.render("/contacts");
});

module.exports = router;
